app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fp_js_form_validator:
    resource: "@FpJsFormValidatorBundle/Resources/config/routing.xml"
    prefix: /fp_js_form_validator

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_security_login:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /login

fos_user_security_check:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /