# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.file_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['@service_container', '%upload_directory%']
    app.media.file:
        class: AppBundle\Service\MediaFile
        arguments: ['%upload_directory%']
    app.media.image:
        class: AppBundle\Service\MediaImage
        arguments: ['@service_container', '%upload_directory%']